### ISSUE TITLE
Decide what the default config should contain

### ISSUE THREAD

**Issue by thibaudcolas** [torchbox/eslint-config-torchbox#1]
We need to decide what our shared config should enforce. Based on a survey of Torchbox projects, I can see three options that seem appropriate for a start:

- Recommended rules from ESLint & plugins we use: react, jsx-a11y, import
- Extend eslint-config-react-app (few opinions), potentially with extra rules turned on
- Extend eslint-config-airbnb (very opinionated), potentially with some rules turned off
  - Something opinionated is useful for learning & getting up to speed
  - Need to check how it differs from CRA’s config exactly
  - Configure line-length – feels like a good one to override

---

For reference, here is the survey of our current ESLint usage this is based on:

- 54 (48 + 6) projects with ESLint
- 32 (26 + 6) projects with eslint-plugin-react
- 13 (7 + 6) projects with eslint-plugin-jsx-a11y
- 13 (7 + 6) projects with eslint-plugin-import
- 7 projects with eslint-config-airbnb
- 6 projects with eslint-config-react-app (https://github.com/facebook/create-react-app/blob/master/packages/eslint-config-react-app/index.js)
- 2 projects with eslint-config-prettier
- 1 project with eslint-plugin-organize-imports
- 1 project with eslint-config-standard
- 0 projects with eslint-plugin-react-hooks

**Comment by thibaudcolas** [comment]
Discussed during today’s meeting:

- eslint-config-airbnb feels like a safe choice
- Since we want to use create-react-app for projects where it is usable, we might want to use CRA’s config for other projects as well – for consistency.
- @thibaudcolas to check in what way the two configurations differ, and judge whether they are similar enough to be interchangeable, or whether we do want to recommend one over the other.

**Comment by thibaudcolas** [comment]
- eslint-config-react-app: https://github.com/facebook/create-react-app/blob/master/packages/eslint-config-react-app/index.js
- eslint-config-airbnb-base: https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/index.js
- eslint-config-airbnb: https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/index.js

After looking into this further, create-react-app’s configuration doesn’t feel as suitable for our purposes. The main difference isn’t in what it enforces but how – CRA’s config uses warnings a lot (instead of errors). Their philosophy is that (in the CRA setup), warnings are equally as visible, and errors should only be used for issues that will likely break the code.

For our projects I think it’s important that no code with a linting issue can be committed / merged (unless someone purposefully disables a rule), so warnings aren’t really suitable. We could use `--max-warnings 0` to treat warnings as errors, but that doesn’t feel right either.

Another issue with CRA’s config is that it has dependencies on ESLint extensions for TypeScript & Flow. While that’s not a problem when the config is installed automagically in create-react-app, this means that projects not using it would need to add those dependencies, even if they don’t use TypeScript or Flow. This could cause confusion, and it’s also not a good feeling to have more dependencies than needed.

So – Airbnb’s config is the way to go as a baseline. I think CRA’s opinions would still be a good starter on CRA projects, but it doesn’t feel appropriate for codebases that have to manage their config manually, and it also doesn’t enforce as much.

**Comment by helenb** [comment]
That sounds a sensible conclusion - just to be clear, I assume projects using CRA would still use the CRA default linting? Will using a different linting configuration (if we wanted to) mean ejecting from the default tooling?  How will we handle the warnings vs errors issues if we use the CRA default for those projects?

**Comment by thibaudcolas** [comment]
We’ve discussed this in person today but I’ll comment here for future reference.

It’s possible to use a custom ESLint config in CRA projects without ejecting, so that’s what I would recommend. Projects doing this would then get the linting feedback from the config they are using instead of CRA’s default, so there would be no risk of overlap.

For whether to use a custom config or not – personally I think that "real-world" projects would want to use stricter linting than what CRA provides out of the box.CRA’s config is geared towards developer errors and doesn’t really try to enforce any conventions, which is important for projects that are worked on by a lot of different people over time in an agency context.
