### ISSUE TITLE
Recommended Typescript config returns Typescript linting errors for .js files

### ISSUE THREAD

**Issue by alxbridge** [torchbox/eslint-config-torchbox#17]
When adding the recommended Typescript config to a project with an existing Javascript codebase, I found that I was being returned `@typescript-eslint` errors for some of those existing files. The following alternative config allows me to apply the previous, `babel-eslint` parsing/linting to the Javascript files, and selectively apply `@typescript-eslint` to the `.ts` & `.tsx` files:

```
module.exports = {
    // See https://github.com/torchbox/eslint-config-torchbox for rules.
    extends: 'torchbox',
    parser: 'babel-eslint',
    overrides: [
        {
            files: ['**/*.ts', '**/*.tsx'],
            extends: [
                'torchbox',
                'plugin:import/typescript',
                'plugin:@typescript-eslint/eslint-recommended',
                'plugin:@typescript-eslint/recommended',
            ],
            parser: '@typescript-eslint/parser',
            plugins: ['@typescript-eslint'],
            rules: {
                'react/jsx-filename-extension': [2, { extensions: ['.tsx'] }],
                'import/extensions': [
                    2,
                    'always',
                    {
                        ignorePackages: true,
                        pattern: {
                            js: 'never',
                            jsx: 'never',
                            ts: 'never',
                            tsx: 'never',
                        },
                    },
                ],
            },
        },
    ],
};
```

If the recommended Typescript config is intended for a mixed js/ts project, should it be something more like the above? (Or, alternatively, should something like the above be added as a separate recommendation for a mixed js/ts project?)

**Comment by thibaudcolas** [comment]
Thank you @alxbridge, I think it makes sense for the recommended config to be mixed, considering that’s very likely on our projects. I’ll replace the current recommendation with what you’ve shared here, with two changes:

- `files: ['**/*.ts', '**/*.tsx'],` I think this can just be `files: ['*.ts', '*.tsx'],`
- `'react/jsx-filename-extension': [2, { extensions: ['.tsx'] }],` In a mixed project it probably makes sense to add `.js` files here.

There hasn’t been many people interested in contributing to this so I’ll update the config right away – please let me know if you’d want to do further changes.

**Comment by thibaudcolas** [comment]
Updated – @alxbridge this config is only used on a couple of projects currently, if you’re actively using it and have more suggestions please do open more issues/PRs!

**Comment by peteandrew** [comment]
@thibaudcolas it is being used on Wagtail Donate https://git.torchbox.com/internal/wagtail-donate/-/blob/master/.eslintrc.js
